# Generated by Django 5.0.2 on 2024-03-29 16:06

import core.models
import django.db.models.deletion
import django.db.models.expressions
import django_extensions.db.fields
import django_resized.forms
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('myauth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Creador',
            fields=[
                ('user', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('logo', django_resized.forms.ResizedImageField(blank=True, crop=['middle', 'center'], force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[200, 200], upload_to=core.models.user_directory_path)),
                ('support_link', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Campania',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('nombre', models.CharField(max_length=100)),
                ('reglamento', models.TextField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to=core.models.campaign_directory_path)),
                ('precio_ticket', models.DecimalField(decimal_places=2, max_digits=9)),
                ('cantidad_tickets', models.IntegerField(choices=[(99, '0'), (999, '1'), (9999, '2'), (99999, '3'), (999999, '4'), (9999999, '5')])),
                ('tickets_necesarios', models.IntegerField()),
                ('ranking_activo', models.BooleanField()),
                ('info_ranking', models.TextField()),
                ('num_visibles', models.BooleanField(blank=True, default=False)),
                ('buyed_tickets', models.IntegerField(blank=True, default=0)),
                ('creador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.creador')),
            ],
        ),
        migrations.CreateModel(
            name='Ofertas',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('cada', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=9)),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campania')),
            ],
        ),
        migrations.CreateModel(
            name='Premios',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campania')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('id_ticket', models.IntegerField()),
                ('campania', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.campania')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='campania',
            constraint=models.CheckConstraint(check=models.Q(('precio_ticket__gte', 0)), name='campania_precio_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='campania',
            constraint=models.CheckConstraint(check=models.Q(('cantidad_tickets__gte', 0)), name='campania_cantidad_no_negativa'),
        ),
        migrations.AddConstraint(
            model_name='campania',
            constraint=models.CheckConstraint(check=models.Q(('tickets_necesarios__gte', 0)), name='campania_tickets_necesarios_no_negativos'),
        ),
        migrations.AddConstraint(
            model_name='campania',
            constraint=models.CheckConstraint(check=models.Q(('tickets_necesarios__lte', django.db.models.expressions.CombinedExpression(models.F('cantidad_tickets'), '+', models.Value(1)))), name='campania_tickets_necesarios_menor_o_igual_cantiad_tickets'),
        ),
        migrations.AddConstraint(
            model_name='campania',
            constraint=models.CheckConstraint(check=models.Q(('buyed_tickets__lt', models.F('cantidad_tickets'))), name='tickets_bought_lower_than_tickets_available'),
        ),
        migrations.AddConstraint(
            model_name='ofertas',
            constraint=models.CheckConstraint(check=models.Q(('precio__gte', 0)), name='precio_no_negativo'),
        ),
        migrations.AddConstraint(
            model_name='ofertas',
            constraint=models.CheckConstraint(check=models.Q(('cada__gte', 0)), name='cada_no_negativo'),
        ),
        migrations.AlterUniqueTogether(
            name='ofertas',
            unique_together={('campania', 'cada')},
        ),
        migrations.AddConstraint(
            model_name='reserva',
            constraint=models.CheckConstraint(check=models.Q(('id_ticket__gte', 0)), name='cantidad_no_negativa'),
        ),
        migrations.AlterUniqueTogether(
            name='reserva',
            unique_together={('campania', 'id_ticket')},
        ),
    ]
